name: receipt_book
description: "A Receipt Maker App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_nav_bar: ^5.0.7
  hugeicons: ^1.1.4
  pdf: ^3.11.3
  flutter_pdfview: ^1.4.3
  printing: ^5.11.0
  firebase_core: ^4.3.0
  google_sign_in: ^6.2.1
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  firebase_database: ^12.1.1
  provider: ^6.1.5+1
  flutter_animate: ^4.5.2
  google_fonts: ^6.3.3
  flutter_slidable: ^4.0.3
  image_picker: ^1.0.4
  http: ^1.6.0
  intl: ^0.20.2
  dropdown_button2: ^2.3.9
  flutter_launcher_icons: ^0.14.4
  internet_connection_checker_plus: ^2.9.1+2
  screenshot: ^3.0.0
  share_plus: ^12.0.1
  image_gallery_saver_plus: ^4.0.1
  permission_handler: ^11.3.0
  shared_preferences: ^2.2.2
  local_auth: ^2.1.6
  toastification: ^3.0.3
  rxdart: ^0.28.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo.png"
